services:
  mysql:
    image: 'mysql:8.0.35'
    container_name: db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=myuser
      - MYSQL_DATABASE=hanghe
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./.data/mysql:/var/lib/mysql
